// frontend_next/src/app/admin/(dashboard)/models/page.tsx
"use client";
import { Card, CardContent } from "@saasfly/ui/card";
import { Button } from "@saasfly/ui/button";
import { Cpu, Plus, Power } from "lucide-react";

const models = [
  { id: 1, name: "deepseek-chat", provider: "DeepSeek", type: "chat", endpoint: "https://api.deepseek.com", primary: true },
  { id: 2, name: "gpt-4o", provider: "OpenAI", type: "chat", endpoint: "https://api.openai.com/v1", primary: false },
  { id: 3, name: "text-embedding-3-small", provider: "OpenAI", type: "embedding", endpoint: "https://api.openai.com/v1", primary: false },
];

export default function ModelsPage() {
  return (<div className="space-y-6">
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900">模型配置</h1><p className="text-sm text-slate-500 mt-1">管理 AI 模型接入与主备切换</p></div><Button className="bg-blue-600 hover:bg-blue-700"><Plus className="h-4 w-4 mr-2"/>添加模型</Button></div>
    <div className="space-y-3">{models.map(m=><Card key={m.id} className="border-[#E4ECFC]"><CardContent className="p-4 flex items-center justify-between"><div className="flex items-center gap-3"><Cpu className="h-5 w-5 text-blue-500"/><div><p className="font-medium">{m.name}<span className="text-xs text-slate-400 ml-2">{m.provider} · {m.type}</span></p><p className="text-xs text-slate-400 mt-0.5">{m.endpoint}</p></div></div><div className="flex items-center gap-3"><span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${m.primary?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{m.primary?"主模型":"备用"}</span><button className="text-slate-400 hover:text-slate-600"><Power className="h-4 w-4"/></button></div></CardContent></Card>)}</div>
  </div>);
}

// frontend_v2/src/views/models/index.vue
<template>
  <div class="geo-page">
    <div class="hero">
      <h1>模型配置</h1>
      <p>管理 AI 模型接入、切换策略和 fallback 配置</p>
      <el-button type="primary">添加模型</el-button>
    </div>
    <div class="mt-6 space-y-4">
      <div v-for="m in models" :key="m.id" class="glass-panel p-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-3">
            <Cpu class="w-5 h-5 text-[var(--color-primary)]" />
            <div>
              <span class="font-semibold">{{ m.name }}</span>
              <span class="text-xs text-[var(--text-muted)] ml-2">{{ m.provider }} · {{ m.type }}</span>
            </div>
          </div>
          <div class="flex items-center gap-2">
            <el-tag :type="m.status === 'active' ? 'success' : 'warning'" size="small">{{ m.status === 'active' ? '主模型' : '备用' }}</el-tag>
            <el-switch v-model="m.enabled" />
          </div>
        </div>
        <div class="mt-2 grid grid-cols-3 gap-4 text-xs text-[var(--text-muted)]">
          <span>端点: {{ m.baseUrl }}</span>
          <span>温度: {{ m.temperature }}</span>
          <span>最大 Token: {{ m.maxTokens }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Cpu } from 'lucide-vue-next'

const models = ref([
  { id: 1, name: 'deepseek-chat', provider: 'DeepSeek', type: 'chat', status: 'active', baseUrl: 'https://api.deepseek.com', temperature: 0.1, maxTokens: 8000, enabled: true },
  { id: 2, name: 'gpt-4o', provider: 'OpenAI', type: 'chat', status: 'fallback', baseUrl: 'https://api.openai.com/v1', temperature: 0.3, maxTokens: 16000, enabled: false },
  { id: 3, name: 'text-embedding-3', provider: 'OpenAI', type: 'embedding', status: 'active', baseUrl: 'https://api.openai.com/v1', temperature: 0, maxTokens: 8191, enabled: true },
])
</script>
